apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    name: app1
spec:
  containers:
  - name: cont1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
