apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
    matchExpressions:
      - {key: tier, operator: In, values: [frontend] }  
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80


kubectl create -f rs.yml

kubectl get po

kubectl get po -o wide

kubectl get po -l tier=frontend

kubectl describe rs nginx-rs

kubectl delete pods nginx-rs-dhbfm

kubectl scale rs nginx-rs --replicas=5

kubectl scale rs nginx-rs --replicas=1

kubectl delete -f rs.yml

https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/