apiVersion: v1
kind: Pod
metadata:
  name: hostpathpod
spec:
  containers:
  - image: nginx
    name: nginxcon
    volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-hostpath
  volumes:
  - name: test-hostpath
    hostPath:
      path: /data
      type: DirectoryOrCreate
