apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
      - name: web-container
        image: nginx

        command: ["/bin/sh"]
        args:
        - -c
        - >
          nginx -g 'daemon off;' & while true; do sleep 10; done
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-service1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver1
