apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - image: nginx
    name: multi-container-pod
  - image: redis
    name: mesagging-server
  - image: memcached
    name: caching-server

