# save as index.html

<html>
 <head>
  <title>Blue</title>
 </head>
 <body bgcolor="#11a7f7">
  <h1>V1</h1>
 </body>
</html>

kubectl create configmap index-blue-v1 --from-file=index.html

blue-deploy.yaml
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: web-version
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: index-blue-v1
---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    color: blue

---
kubectl create -f blue-deploy.yaml


https://blog.nillsf.com/index.php/2019/11/10/simple-kubernetes-blue-green-deployments/