apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetdemo
spec:
  replicas: 5
  selector:
    matchLabels:
      segment: business
  template:
    metadata:
      labels:
        segment: business
    spec:
      containers:
      - name: web-server
        image: nginx:1.20
