apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: version2
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: web-server
  template:
    metadata:
      labels:
        tier: web-server
    spec:
      containers:
      - name: web-server
        image: nginx:1.18
