apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.9
          ports:
           - containerPort: 80

kind: Service
apiVersion: v1
metadata:
  name:  clusteripservice
spec:
  selector:
    app:  nginx-temp
  type:  ClusterIP
  ports:
  - name:  webport
    port:  80 #on host
    targetPort:  80 #on pod