apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb1
  name: bb1
spec:
  containers:
  - image: busybox
    name: bb1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
