apiVersion: v1
kind: Pod
metadata:
  name: busybox-empdir
  namespace: default
spec:
  containers:
  - image: busybox
    name: busyempcontainer
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /myempdir
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir: {}


    single container empty dir mapping
___________________________________
$ kubectl apply -f busybox-emptyDir.yml
pod/busybox created
$ kubectl get pods
NAME      READY   STATUS    RESTARTS   AGE
busybox   1/1     Running   0          9s
$ kubectl exec -it busybox -- sh
/ # df -h /scratch
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/rhel-var     60.0G      2.5G     57.5G   4% /scratch
/ # exit
$ kubectl delete -f busybox-emptyDir.yml
pod "busybox" deleted
