apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
 # Encoded value: echo -n 'secret'|base64
  password: c2VjcmV0

  #kubectl create secret generic my-test-secret --from-literal=password=secret
  #kubectl describe secret my-test-secret
  #kubectl get secret my-test-secret -o go-template='{{.data}}'
##https://mariadb.org/mariadb-k8s-create-a-secret-and-use-it-in-mariadb-deployment/