apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80


kubectl create -f rc.yml

kubectl get pods

kubectl get po -l app=nginx-app

kubectl describe rc nginx-rc


kubectl scale rc nginx-rc --replicas=5

kubectl get pods -l app=nginx-app -o wide

kubectl delete -f rc.yml
