apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-nginx
    image: nginx
    ports:
    - containerPort: 80
      name:  http
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-vol
  volumes:
    - name: test-vol
      hostPath:
        path: /root/kvol
  restartPolicy: Never
